openapi: 3.0.0
info:
  description: "Test swagger specification"
  version: "1.0.0"
  title: "Test swagger specification"
  contact:
    email: "andre@nullzueins.com"
servers:
  - url: http://127.0.0.1:3000/
    description: Localhost (uses test data)
paths:
  /status:
    get:
      description: Status route, so we can check if server is alive
      tags:
        - Status
      parameters:
        - name: health
          in: query
          description: Service status
          required: true
          schema:
            type: boolean
            default: true

      responses:
        200:
          description: 'Server is alive'
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                     type: boolean
                  date:
                     type: string
                example:
                  health: true 
                  date: "2018-02-19T15:36:46.758Z"
  /image/$id:
    get:
      description: Get image
      tags:
        - Image
      responses:
        200:
          description: 'The illustration'
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileName:
                     type: string
                  description:
                     type: string
                example:
                 fileName: kids-playing-with-a-ball.jpg
                 description: "Kids playing with a ball"
