openapi: 3.0.0
info:
  title: Kita day planner
  description: API to generate kita day planner pdf
  version: 1.0.0
  contact:
    email: andre@nullzueins.com
  license:
    name: MIT
  termsOfService: /api-terms-service
servers:
  - url: http://0.0.0.0:3000/
    description: Localhost (uses test data)
  - url: https://day-planner-service.herokuapp.com/
    description: Staging (uses test data)
  - url: https://kita-date-planner.nullzueins.com/
    description: Production (uses live data)
externalDocs: 
  - url: https://github.com/nullzueins/kindergarten-day-planner-service/
    description: Find more info on GitHub repository
produces: 
  - application/json
  - application/pdf
tags:
  - name: Image
    description: Images of Kita day planner
  - name: PDF
    description: Kita day planner pdf
schemes:
  - http
  - https
uiConfig:
    docExpansion: full
    deepLinking: true
    defaultModelRendering: schema
    
paths:
  /images:
    get:
      description: Get image
      tags:
        - Image
      responses:
        200:
          description: All images
          content:
            application/json:
              schema:
                type: object
                example:
                  - id: 12
                    filename: image_12.jpg
                    description: Image description for image 12
                  - id: 42
                    filename: image_42.jpg
                    description: Image description for image 42

  /image:
    get:
      description: Get image
      tags:
        - Image
      responses:
        200:
          description: The illustration
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title: Image identifier
                  description: The inditifier of the requested image
      parameters:
      - in: query
        name: id
        title: Image identifier
        description: The inditifier of the requested image
        required: true
        schema:
          type: integer
          format: int64
          minimum: 0
          maximum: 14

  /pdf:
    get:
      description: "**Generate** pdf with images."
      tags:
        - PDF
      parameters:
        - in: query
          name: image
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
              minimum: 0
              maximum: 14
            minItems: 1
            maxItems: 15
          example:
            id: 
            - 12
            - 144
          style: matrix
          explode: true
      responses:
        200:
          description: Returns an generated PDF with the selected images included.
          content:
            application/pdf:
              schema:
                type: file
            application/json:
              schema:
                type: object
              example:
                cache: true
                url: https://day-planner-service.herokuapp.com/downloads/tagesplaner_14-9.pdf
